In [1]:
import psycopg2
import sqlalchemy
import pandas as pd

In [2]:
db_engine = sqlalchemy.create_engine('postgresql://sgqokpuggkrkve:ff59f8ca03f950cef2e98fb4ae4ff44bdf7136ff37da62215672902c613297d6@ec2-18-211-172-50.compute-1.amazonaws.com:5432/d3mhp3r7jhume9')

In [3]:
df = pd.read_sql_query("select * from label",con=db_engine)
df

,uuid,user_id,docid,model,nonfactual_spans,evidence,error_type,summary,dialogue
0,b8d502c5-1fa8-4b54-930b-8203eac9a9f9,sanjana,13611370,gpt4-32k-0613,None,None,None,Derek asked Judy if she could feed his animals...,"Derek: Judy, r you leaving for the weekend?\r\..."
1,47ff76cb-c241-435f-8e7f-c72db969bcaf,sanjana,13611426,gpt4-32k-0613,None,None,None,Poppy and Harry both share a preference for Li...,Poppy: Yeah. I definitely prefer Lisbon\r\nHar...
2,63d06a97-c9f1-490f-bbfd-4b4a0d5586f2,sanjana,13611442,gpt4-32k-0613,None,None,None,"Helen reached out to Simon, let him know she h...","Helen: Hey, Simo, are you there?\r\nSimon: Yep..."
3,a65985ea-6cc5-414c-8112-81b45a9dca51,sanjana,13611508,gpt4-32k-0613,None,None,None,"Martha, who does not know Ophelia, reaches out...","Martha: Hey, can I ask you a question?\r\nOphe..."
4,21546deb-2628-464e-b81c-208d7f3d432e,sanjana,13611559,gpt4-32k-0613,None,None,None,Rashi is confused about choosing a career due ...,"Teacher: Rashi, why are you so low? \r\nRashi:..."
...,...,...,...,...,...,...,...,...,...
216,6e082568-67f7-4bcf-919a-2fccc0be3381,sanjana,13828511,gpt4-32k-0613,None,None,None,Willyx mistakenly asked Alicja about a job int...,Willyx: how did your job interview go?\r\nAlic...
217,8a0f088f-adb1-4b01-9adb-42e93115bd0f,ann_kprt,13611370,gpt4-32k-0613,None,None,None,Derek asked Judy if she could feed his animals...,"Derek: Judy, r you leaving for the weekend?\r\..."
218,9f364d13-2041-4911-9c57-53d70e5ec04c,ann_kprt,13611426,gpt4-32k-0613,None,None,None,Poppy and Harry both share a preference for Li...,Poppy: Yeah. I definitely prefer Lisbon\r\nHar...
219,a7cb0324-122a-47f5-9754-86769760cc3d,ann_kprt,13611442,gpt4-32k-0613,None,None,None,"Helen reached out to Simon, let him know she h...","Helen: Hey, Simo, are you there?\r\nSimon: Yep..."
220,2fcf9058-e7ad-41ae-babb-ef9a8eafd20a,ann_kprt,13611508,gpt4-32k-0613,None,None,None,"Martha, who does not know Ophelia, reaches out...","Martha: Hey, can I ask you a question?\r\nOphe..."

In [16]:
df_transformer = pd.read_csv('/home/sanjana/factual_evaluation_source_based/datasets/sota_annotations/dialogue_aggrefact.csv')

In [26]:
for idx, row in df_transformer.iterrows():
    if 'dick' in row['Dialogue']:
        print(row)

Unnamed: 0                                                     570
DocID                                                     13727853
Dialogue         Jen: I think I'm through with the dickhead. He...
Model                                                    human_ref
Summary          Jen is about to break up with her boyfriend. J...
w/ Error                                                         0
CorefE                                                         NaN
CorefE_text                                                    NaN
CircE                                                          NaN
CircE_text                                                     NaN
OutE                                                           NaN
OutE_text                                                      NaN
GramE                                                          NaN
GramE_text                                                     NaN
PredE                                                          NaN
PredE_text                                                     NaN
SubjObjE                                                       NaN
SubjObjE_text                                                  NaN
OtherE                                                         0.0
OtherE_text                                                    NaN
LinkE                                                          NaN
LinkE_text                                                     NaN
origin                                                     FacEval
Name: 570, dtype: object
Unnamed: 0                                                     571
DocID                                                     13727853
Dialogue         Jen: I think I'm through with the dickhead. He...
Model                                                   bart_large
Summary          Jen wants to break up with her partner. She do...
w/ Error                                                         0
CorefE                                                         NaN
CorefE_text                                                    NaN
CircE                                                          NaN
CircE_text                                                     NaN
OutE                                                           NaN
OutE_text                                                      NaN
GramE                                                          NaN
GramE_text                                                     NaN
PredE                                                          NaN
PredE_text                                                     NaN
SubjObjE                                                       NaN
SubjObjE_text                                                  NaN
OtherE                                                         0.0
OtherE_text                                                    NaN
LinkE                                                          NaN
LinkE_text                                                     NaN
origin                                                     FacEval
Name: 571, dtype: object
Unnamed: 0                                                     572
DocID                                                     13727853
Dialogue         Jen: I think I'm through with the dickhead. He...
Model                                                mv-bart_large
Summary          Jen is going to tell her partner to move out. ...
w/ Error                                                         0
CorefE                                                         NaN
CorefE_text                                                    NaN
CircE                                                          NaN
CircE_text                                                     NaN
OutE                                                           NaN
OutE_text                                                      NaN
GramE                                                          NaN
GramE_text                                                     NaN
PredE                                                          NaN
PredE_text                                                     NaN
SubjObjE                                                       NaN
SubjObjE_text                                                  NaN
OtherE                                                         0.0
OtherE_text                                                    NaN
LinkE                                                          NaN
LinkE_text                                                     NaN
origin                                                     FacEval
Name: 572, dtype: object
Unnamed: 0                                                     573
DocID                                                     13727853
Dialogue         Jen: I think I'm through with the dickhead. He...
Model                                            co-ref bart large
Summary          Jen is going to tell her boyfriend to move out...
w/ Error                                                         0
CorefE                                                         NaN
CorefE_text                                                    NaN
CircE                                                          NaN
CircE_text                                                     NaN
OutE                                                           NaN
OutE_text                                                      NaN
GramE                                                          NaN
GramE_text                                                     NaN
PredE                                                          NaN
PredE_text                                                     NaN
SubjObjE                                                       NaN
SubjObjE_text                                                  NaN
OtherE                                                         0.0
OtherE_text                                                    NaN
LinkE                                                          NaN
LinkE_text                                                     NaN
origin                                                     FacEval
Name: 573, dtype: object
Unnamed: 0                                                     574
DocID                                                     13727853
Dialogue         Jen: I think I'm through with the dickhead. He...
Model                                         condigsum bart large
Summary          Jen wants to break up with her boyfriend. She ...
w/ Error                                                         0
CorefE                                                         NaN
CorefE_text                                                    NaN
CircE                                                          NaN
CircE_text                                                     NaN
OutE                                                           NaN
OutE_text                                                      NaN
GramE                                                          NaN
GramE_text                                                     NaN
PredE                                                          NaN
PredE_text                                                     NaN
SubjObjE                                                       NaN
SubjObjE_text                                                  NaN
OtherE                                                         0.0
OtherE_text                                                    NaN
LinkE                                                          NaN
LinkE_text                                                     NaN
origin                                                     FacEval
Name: 574, dtype: object

In [19]:
df_transformer[~df_transformer['DocID'].isin(list(df['dialogue'].values))]

,Unnamed: 0,DocID,Dialogue,Model,Summary,w/ Error,CorefE,CorefE_text,CircE,CircE_text,...,GramE_text,PredE,PredE_text,SubjObjE,SubjObjE_text,OtherE,OtherE_text,LinkE,LinkE_text,origin
1186,36,13828456,Bailey: <file_other>\r\nBailey: ....\r\nMikael...,BART,Bailey has a lot of fabric in his closet. He k...,1,0.0,NaN,1.0,at Ikea,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1187,37,13828456,Bailey: <file_other>\r\nBailey: ....\r\nMikael...,UniLM,Bailey has a lot of fabric in his closet and h...,0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1188,38,13828456,Bailey: <file_other>\r\nBailey: ....\r\nMikael...,MV-BART,Bailey has a lot of fabric in her closet. She ...,1,0.0,NaN,1.0,at Ikea,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1189,39,13828456,Bailey: <file_other>\r\nBailey: ....\r\nMikael...,CODS,Mikaela had to buy a box of fabric at IKEA bec...,1,0.0,NaN,0.0,NaN,...,NaN,1.0,won't,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1202,52,13727579,Mum: hungry?\r\nSteve: starving...\r\nMum: I'l...,BART,Mum will wrap something up for Steve.,0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1513,363,13829773,"Ola: Hello Kate, sorry for not keeping in touc...",CODS,Ola and her family are travelling in Cuba. The...,1,1.0,They,0.0,NaN,...,NaN,1.0,are travelling in Cuba,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1518,368,13819472,Jenny: Are we going to that concert on Saturda...,BART,"Jenny, Jeremy and Joan are going to the concer...",0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1519,369,13819472,Jenny: Are we going to that concert on Saturda...,UniLM,"Jenny , Jeremy and Joan are going to the conce...",0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1520,370,13819472,Jenny: Are we going to that concert on Saturda...,MV-BART,"Jenny, Jeremy and Joan are going to the concer...",0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1521,371,13819472,Jenny: Are we going to that concert on Saturda...,CODS,"Jenny, Jeremy and Joan are going to a concert ...",1,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum

In [18]:
df_transformer

,Unnamed: 0,DocID,Dialogue,Model,Summary,w/ Error,CorefE,CorefE_text,CircE,CircE_text,...,GramE_text,PredE,PredE_text,SubjObjE,SubjObjE_text,OtherE,OtherE_text,LinkE,LinkE_text,origin
0,0,13809941,Thelma: i dont have anything to wear\nLouisa: ...,human_ref,Louisa will lend Thelma her red velvet dress.,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,FacEval
1,1,13809941,Thelma: i dont have anything to wear\nLouisa: ...,bart_large,Thelma doesn't have anything to wear. Louisa w...,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,FacEval
2,2,13809941,Thelma: i dont have anything to wear\nLouisa: ...,mv-bart_large,Thelma doesn't have anything to wear. Louisa w...,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,FacEval
3,3,13809941,Thelma: i dont have anything to wear\nLouisa: ...,co-ref bart large,Thelma doesn't have anything to wear. Louisa w...,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,FacEval
4,4,13809941,Thelma: i dont have anything to wear\nLouisa: ...,condigsum bart large,Louisa will bring Thelma her red velvet dress.,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,FacEval
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1545,395,13864835,Tony: <photo_file>\nAmy: Sweet little cat <3\n...,CODS,Amy sends Lucas a photo of a cat.,1,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,1.0,Amy,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1546,396,13727934,"Patricia: Hey, could you give me a call in an ...",BART,George will call Patricia in an hour.,0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1547,397,13727934,"Patricia: Hey, could you give me a call in an ...",UniLM,George will call Patricia in an hour or so bec...,1,1.0,she,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1548,398,13727934,"Patricia: Hey, could you give me a call in an ...",MV-BART,Patricia wants George to call her in an hour.,0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum
1549,399,13727934,"Patricia: Hey, could you give me a call in an ...",CODS,Patricia wants George to call her in an hour. ...,0,0.0,NaN,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,RefMatters_SAMSum

In [ ]:
df_transformer = pd.read_csv('/home/sanjana/factual_evaluation_source_based/datasets/sota_annotations/dialogue_aggrefact.csv')

In [6]:
conn = psycopg2.connect(
   database="dd6goghvt02djh", 
    user='ppqbjimormsthy', 
    password='ef920ec6553ab7d225dbf61927f1c8ca28e002ce8ca6dbed67d31deb230ec7f0', 
    host='ec2-52-20-78-241.compute-1.amazonaws.com', 
    port = '5432'
    
)

OperationalError: connection to server at "ec2-52-20-78-241.compute-1.amazonaws.com" (52.20.78.241), port 5432 failed: FATAL:  role "ppqbjimormsthy" is not permitted to log in

In [3]:
cursor = conn.cursor()

sql_drop = '''DROP TABLE IF EXISTS generated_summaries;'''
cursor.execute(sql_drop)
conn.commit()

In [4]:
sql_drop = '''DROP TABLE IF EXISTS label;'''
cursor.execute(sql_drop)
conn.commit()

OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.